version: '3'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres13:/var/lib/postgresql/data
  redis:
    image: redis:7.0.15-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  web:
    build: .
    command: >
      /bin/bash -c "bin/setup
         bundle exec rails db:seed
         bundle exec whenever --update-crontab
         bundle exec rails s -b 0.0.0.0"
         bundle exec sidekiq
    volumes:
      - .:/rails
      - rubygems:/usr/local/bundle
    depends_on:
      - db
      - redis
      - sidekiq
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/myapp_development
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    ports:
      - 3000:3000

  test:
    build: .
    command: >
      /bin/bash -c "bin/setup && bundle exec rspec"
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/myapp_test
      DATABASE_CLEANER_ALLOW_PRODUCTION: true
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
      RAILS_ENV: test
      REDIS_URL: redis://redis:6379/0
    ports:
      - 3000:3000
volumes:
  postgres13:
  redis_data:
  rubygems:
