abandoned_cart:
  cron: "* * * * *"
  class: "MarkCartsAbandonedJob"
  queue: mark_carts_abandoned

remove_abandoned_cart:
  cron: "* * * * *"
  class: "RemoveCartsAbandonedJob"
  queue: remove_carts_abandoned

